# CMSC 197 - Machine Learning

## Assignment 1: Introduction to Numerical Computing Using Python

### Submitted by: Limuelle Alamil - BSCS IV - Section 1 

## Part 1

In [2]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


#### The first 1D array - ŷ

In [206]:
ŷ = np.linspace(-1, 1, num=20)
ŷ

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

#### The second 1D array - y 

In [205]:
y = np.linspace(0, 1, num=20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Shape and dimension of ŷ

In [207]:
print("The shape of ŷ is " + str(ŷ.shape) + ".")

The shape of ŷ is (20,).


In [208]:
print("ŷ is " + str(ŷ.ndim) + "-dimensional.")

ŷ is 1-dimensional.


#### Shape and dimension of y

In [209]:
print("The shape of y is " + str(y.shape) + ".")

The shape of y is (20,).


In [210]:
print("y is " + str(y.ndim) + "-dimensional.")

y is 1-dimensional.


### Loss Functions

#### Mean Squared Error 

In [211]:
def mse(ŷ, y):
    loss = np.mean((ŷ - y) ** 2)
    return loss

print("MSE: " + str(mse(ŷ, y)))

MSE: 0.3421052631578948


#### Mean Absolute Error

In [212]:
def mae(ŷ, y):
    loss = np.mean(abs(ŷ - y))
    return loss

print("MAE: " + str(mae(ŷ, y)))

MAE: 0.4999999999999999


#### Mean Squared Logarithmic Error

In [213]:
def msle(ŷ, y):
    num_of_neg_ŷ = (ŷ<0).sum() # number of negative values in ŷ
    num_of_neg_y = (y<0).sum() # number of negative values in y
    
    # proceed to calculation if there are no negative values
    if (num_of_neg_ŷ <= 0 and num_of_neg_y <= 0):
        loss = np.mean((np.log10(ŷ + 1) - np.log10(y + 1)) ** 2)
        return loss
    # stop if there are negative values; log of negative values will result to Math Error
    else:
        return "ERROR: You cannot perform MSLE on negative targets."
    

print("MSLE: " + str(msle(ŷ, y)))

MSLE: ERROR: You cannot perform MSLE on negative targets.


####  Mean Absolute Percentage Error

In [214]:
def mape(ŷ, y):
    num_of_neg_y = (y==0).sum() # number of 0s in y array
    
    # proceed to calculation if there are no 0s in y array
    if (num_of_neg_y <= 0):
        loss = np.mean(abs((ŷ - y) / y))
        return format(loss, '.4%')
    # stop if there are 0s in y array; we cannot divide by 0
    else:
        return "ERROR: You cannot divide by 0."

print("MAPE: " + str(mape(ŷ, y)))

MAPE: ERROR: You cannot divide by 0.


## Part 2 

#### The 1D array M created using arange function

In [109]:
M = np.arange(1, 17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Reshaping M into a 4x4 array and transferring to N

In [136]:
N = M.reshape(4, 4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Getting the 2nd row of N 

In [111]:
N[1, 0:4]

array([5, 6, 7, 8])

#### Getting the minimum values for each column of N 

In [139]:
np.min(N, axis = 1)

array([ 1,  5,  9, 13])

<p>Here's a prettier way to present the minimum values of each row without using the axis.</p>

In [138]:
def colmin(N):
    row, col = N.shape
    for i in range(row):
        print("The min value in row " + str(i + 1) + " is: " + str(np.min(N[i, 0:col])) + ".")

colmin(N)

The min value in row 1 is: 1.
The min value in row 2 is: 5.
The min value in row 3 is: 9.
The min value in row 4 is: 13.


#### The location of the minimum value of every row 

In [140]:
def colmin_loc(N):
    row, col = N.shape
    for i in range(row):
        # the row
        row_arr = N[i, 0:col]
        # location of min value on the y-axis
        loc_in_row = i
        # location of min value on the x-axis
        loc_in_col = np.argmin(row_arr)
        # location of the min value
        loc = (loc_in_row, loc_in_col)
        print("Row " + str(i) + "'s min value is located at " + str(loc) + ".")

colmin_loc(N)

Row 0's min value is located at (0, 0).
Row 1's min value is located at (1, 0).
Row 2's min value is located at (2, 0).
Row 3's min value is located at (3, 0).


#### Getting the average of the matrix N 

In [215]:
ave = np.average(N)
print("The average of matrix N is " + str(ave) + ".")

The average of matrix N is 8.5.


#### Creating the vector V 

In [153]:
V = np.ones((4, 1))
V

array([[1.],
       [1.],
       [1.],
       [1.]])

#### Dot product of N and V 

In [154]:
np.dot(N, V)

array([[10.],
       [26.],
       [42.],
       [58.]])